#!/bin/bash
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
export VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0

/home/steve/venvs/vllm/bin/vllm serve google/gemma-4-26B-A4B-it \
        --trust-remote-code \
        --tensor-parallel-size 4 \
        --max-model-len 262144 \
        --enable-prefix-caching \
        --enable-auto-tool-choice \
        --tool-call-parser gemma4 \
        --reasoning-parser gemma4 \
        --speculative-config '{"model":"/home/steve/models/gemma-4-26B-A4B-it-assistant","num_speculative_tokens":3}' \
        --max-num-seqs 8 \
        --max-num-batched-tokens 32768 \
        --kv-cache-dtype auto \
        --compilation-config '{"cudagraph_capture_sizes":[1,2,4,8]}' \
        --gpu-memory-utilization 0.97 \
        --default-chat-template-kwargs '{"enable_thinking":true}'
